// import { Inter } from "next/font/google";
// import "./globals.css";
// import Head from "@/Components/Head";
// import TawkToComponent from "@/Components/TawkToComponent";
// import { GoogleTagManager } from '@next/third-parties/google'

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "UK Top Ranked Academic Helpers - Academians UK",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <GoogleTagManager gtmId="GTM-TMWZ98XS"/>
//       <body
//         className={inter.className}
//       >
//         <Head/>
        
//         {children}
//         {/* <TawkToComponent/> */}
//       </body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import Script from "next/script"; // Import Script from Next.js
import "./globals.css";
import Head from "@/Components/Head";
import TawkToComponent from "@/Components/TawkToComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UK Top Ranked Academic Helpers - Academians UK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Google Tag Manager Script */}
      <Script
        strategy="afterInteractive"
        src="https://www.googletagmanager.com/gtag/js?id=GTM-TMWZ98XS"
      />
      <Script
        id="gtag-init"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'GTM-TMWZ98XS');
          `,
        }}
      />

      <body className={inter.className}>
        <Head />
        {children}
        {/* <TawkToComponent /> */}
      </body>
    </html>
  );
}




