// import { Inter } from "next/font/google";
// import "./globals.css";
// import Head from "@/Components/Head";
// import TawkToComponent from "@/Components/TawkToComponent";
// import { GoogleTagManager } from '@next/third-parties/google'

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "UK Top Ranked Academic Helpers - Academians UK",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <GoogleTagManager gtmId="GTM-TMWZ98XS"/>
//       <body
//         className={inter.className}
//       >
//         <Head/>
        
//         {children}
//         {/* <TawkToComponent/> */}
//       </body>
//     </html>
//   );
// }

// import { Inter } from "next/font/google";
// import Script from "next/script"; // Import Script from Next.js
// import "./globals.css";
// import Head from "@/Components/Head";
// import TawkToComponent from "@/Components/TawkToComponent";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "UK Top Ranked Academic Helpers - Academians UK",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       {/* Google Tag Manager Script */}
//       <Script
//         strategy="afterInteractive"
//         src="https://www.googletagmanager.com/gtag/js?id=GTM-TMWZ98XS"
//       />
      

//       <body className={inter.className}>
//         <Head />
//         {children}
//         {/* <TawkToComponent /> */}
//       </body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import Script from "next/script"; 
import Head from "next/head"; 
import "./globals.css";
import TawkToComponent from "@/Components/TawkToComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UK Top Ranked Academic Helpers - Academians UK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Other head elements here */}
      </Head>

      {/* Google Tag Manager Script */}
      <Script
        id="google-tag-manager"
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtm.js?id=GTM-TMWZ98XS`}
      />

      <body className={inter.className}>
        {/* Google Tag Manager noscript fallback */}
        <noscript
          dangerouslySetInnerHTML={{
            __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TMWZ98XS" 
              height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
          }}
        />
        {children}
        {/* <TawkToComponent /> */}
      </body>
    </html>
  );
}





